[[main]]
identifier = 'home'
name = 'ホーム'
weight = 1
url = '/'
[main.params]
icon = 'home'


# content/page/about/index.md w=2
# content/page/search/index.md w=3
# content/page/archives/index.md w=4
# content/page/qr/index.md    w=5

[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"
weight = 1
[social.params]
icon = "rss"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/rin2yh"
weight = 2
[social.params]
icon = 'brand-github'

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://x.com/rin2yh"
weight = 3
[social.params]
icon = "brand-twitter"

# Zennは記事側からキュレーション的に参照しているため、socialの並びからは外している。
# アイコン（assets/icons/zenn-logo.svg）は復活させる可能性を考えて残す。

[[social]]
identifier = "slides"
name = "Slides"
url = "https://slides.rin2yh.com"
weight = 5
[social.params]
icon = "presentation"

[[social]]
identifier = "games"
name = "Games"
url = "https://games.rin2yh.com"
weight = 6
[social.params]
icon = "device-gamepad"

