[[main]]
identifier = 'home'
name = 'ホーム'
weight = 1
url = '/'
[main.params]
icon = 'home'


# content/page/about/index.md w=2
# content/page/search/index.md w=3
# content/page/archives/index.md w=4

[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"
weight = 1
[social.params]
icon = "rss"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/rin2yh"
weight = 2
[social.params]
icon = 'brand-github'

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://x.com/rin2yh"
weight = 3
[social.params]
icon = "brand-twitter"

[[social]]
identifier = "zenn"
name = "Zenn"
url = "https://zenn.dev/rinrin_yuuki"
weight = 4
[social.params]
icon = "zenn-logo"


[[social]]
identifier = "slides"
name = "Slides"
url = "https://slides.rin2yh.com"
weight = 5
[social.params]
icon = "presentation"

[[main]]
identifier = 'games'
name = 'ゲーム'
weight = 6
url = 'https://games.rin2yh.com'
[main.params]
icon = 'device-gamepad'

