[[main]]
identifier = 'home'
name = 'Home'
weight = 1
url = '/'
[main.params]
icon = 'home'

[[main]]
identifier = 'post'
name = 'Post'
weight = 2
url = '/post'
[main.params]
icon = 'article'

# content/page/search/index.md w=3

# content/page/archives/index.md w=5

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/rin2yh"
[social.params]
icon = 'brand-github'

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://x.com/rin2yh"

[social.params]
icon = "brand-twitter"